name: actionAzARMDeploy

on:
  workflow_dispatch:

env:
  subscriptionId: 61b6a2a9-c491-4d26-ad5f-a11e3aebdcdb

jobs:
  armDeployment:
    name: Deploy ARM Template
    runs-on: ubuntu-latest
    env:
      resource_group_name: ResourceGroup1
      location: eastus

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./Labs/03/az104-03b-md-template.json
          parameters:
            diskName="az104-03a-disk1"
            location="${{ env.location }}"
            sku="Standard_LRS"
            diskSizeGb=32
            sourceResourceId=
            createOption="empty"
            diskEncryptionSetType="EncryptionAtRestWithPlatformKey"
            networkAccessPolicy="AllowAll"

          deploymentName: ${{ env.resource_group_name }}

