name: actionAzWorkflows2

on:
  workflow_dispatch:

env:
  resource_group_name: createPrivateEndpointQS-rg
  vmName: vm-namigaji01
  artifactRetention: 1
  
jobs:
  azureCLIAction:
    name: Test running Azure CLI Workflow
    runs-on: ubuntu-latest
    env:
      location: westus

    steps:
      - uses: actions/checkout@v3

      # Azure Login:  https://github.com/Azure/login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure CLI:  https://github.com/Azure/cli
      - name: Run Azure CLI
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group list
            az deployment group list --resource-group "${{ env.resource_group_name }}"

      - name: Run Azure CLI script
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh
            $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh "${{ env.resource_group_name }}"
