name: actionAzARMDeploy

on:
  workflow_dispatch:

env:
  subscriptionId: 32816311-ade2-448c-9f66-81dc2e916bfb

jobs:
  armDeployment:
    name: Deploy ARM Template
    runs-on: ubuntu-latest
    env:
      resource_group_name: ResourceGroup1
      location: eastus

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

