name: actionAzWorkflows

on:
  workflow_dispatch:

env:
  subscriptionId: efb5c385-f1e6-46ce-a962-34cf856ebe08

jobs:
  azureCLIAction:
    name: Test running Azure CLI Workflow
    runs-on: ubuntu-latest
    env:
      resource_group_name: az104-03c-rg1
      location: eastus

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure CLI
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group list
            az deployment group list --resource-group "${{ env.resource_group_name }}"

      - name: Run Azure CLI script
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh
            $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh "${{ env.resource_group_name }}"
      
  azurePowerShellAction:
    name: Test running Azure PowerShell Workflow
    runs-on: ubuntu-latest
    env:
      resource_group_name: az104-03c-rg1
      location: eastus

    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 
        
      - name: Run Azure PowerShell
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Get-AzResourceGroup -Name "${{ env.resource_group_name }}"
          azPSVersion: "latest"

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        with:
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/workflows/scripts/azureAzPowerShell.ps1
            $GITHUB_WORKSPACE/workflows/scripts/azureAzPowerShell.ps1
          azPSVersion: "latest"
