name: actionAzARMDeploy

on:
  workflow_dispatch:

env:
  subscriptionId: 00e0fe3d-22f6-4664-9303-dcb3fd6ee484

jobs:
  armDeployment:
    name: Deploy ARM Template
    runs-on: ubuntu-latest
    env:
      resource_group_name: az104-03a-rg1
      location: eastus

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: "${{ env.subscriptionId }}"
          resourceGroupName: "${{ env.resource_group_name }}"
          region: "${{ env.location }}"
          template: ./Labs/03/az104-03b-md-template.json
          parameters:
            diskName="az104-03a-disk1"
            location="${{ env.location }}"
            sku="Standard_LRS"
            sourceResourceId=""
            diskSizeGb=32
            createOption="empty"
            diskEncryptionSetType="EncryptionAtRestWithPlatformKey"
            networkAccessPolicy="AllowAll"

          deploymentName: ${{ env.resource_group_name }}

