name: actionAzWorkflows

on:
  workflow_dispatch:

env:
  resource_group_name: rg-namigaji
needs:
jobs:
  azureCLIAction:
    name: Test running Azure CLI Workflow
    runs-on: ubuntu-latest
    env:
      location: westus

    steps:
      - uses: actions/checkout@v3

      # Azure Login:  https://github.com/Azure/login
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure CLI:  https://github.com/Azure/cli
      - name: Run Azure CLI
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group list
            az deployment group list --resource-group "${{ env.resource_group_name }}"

      - name: Run Azure CLI script
        uses: Azure/CLI@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh
            $GITHUB_WORKSPACE/workflows/scripts/azureAzCLI.sh "${{ env.resource_group_name }}"
      
  azurePowerShellAction:
    name: Test running Azure PowerShell Workflow
    runs-on: ubuntu-latest
    env:
      location: eastus

    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      # Azure PowerShell:  https://github.com/Azure/powershell        
      - name: Run Azure PowerShell
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Get-AzSubscription -SubscriptionId "${{ secrets.subscriptionId }}"
            Get-AzResourceGroup -Name "${{ env.resource_group_name }}"
          azPSVersion: "latest"

      - name: Run Azure PowerShell Script File
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            ./workflows/scripts/azureAzPowerShell.ps1
          azPSVersion: "latest"
          
      # https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmruncommand?view=azps-10.0.0
      - name: Run Azure PowerShell Invoke-AzVMRun Command on an existing Azure VM
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            Invoke-AzVMRunCommand -ResourceGroupName ${{ env.resource_group_name }} `
              -VMName vm-namugaji01 `
              -CommandId 'RunPowerShellScript' `
              -ScriptPath ./bin/install-Bicep.ps1          
          azPSVersion: "latest"

      - name: Deploy a Bicep Template to create an Azure Resource WebApp
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ secrets.subscriptionId }}
          deploymentName: ${{ env.resource_group_name }}
          template: ./bicep/modules/webApp.bicep
          parameters:  helloWorld=true
          failOnStdErr: false
